# TODO: Define the Workflow Name
name: calculator-app-workflow

# TODO: Define triggers for the workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - name: Checkout code fron frontend
        uses: actions/checkout@v3
      # TODO: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 14
      # TODO: Install dependencies
      - name: Install dependencies of frontend
        run: npm install
        working-directory: ./Project/frontend
      # TODO: Run tests
      # - name: Run frontend tests
      #   run: npm test
      #   working-directory: ./Project/frontend
      # TODO: Build the React app
      - name: build frontend final
        run: npm run build
        working-directory: ./Project/frontend

  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - name: Checkout code for backend
        uses: actions/checkout@v3
      # TODO: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.9
      # TODO: Install dependencies
      - name: Install dependencies for backend
        run: |
          python -m pip install --upgrade pip
          pip install -r Project/backend/requirements.txt
      # TODO: Run tests
      - name: Run backend test
        run: python -m unittest discover
        working-directory: ./Project/backend

  # TODO: Define a job for building and pushing Docker images
  docker:
    needs:
      - frontend
      - backend
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    runs-on: ubuntu-latest
    steps:
      # TODO: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      # TODO: Setup Docker
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      # TODO: Build frontend Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build frontend Docker image
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v4
        with: 
          context: ./Project/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-frontend:latest
      # TODO: Build backend Docker image
      - name: Build backend Docker image
        if: github.ref_name == 'master'
        uses: docker/build-push-action@v4
        with:
          context: ./Project/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest
      # TODO: Push images to Docker Hub (if on main branch)

  # OPTIONAL: Define a deployment job (if applicable)
  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
      # TODO: Add deployment steps